# permissions for end users to view gitagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitagent-viewer-role
rules:
- apiGroups:
  - aws.gitops.com
  resources:
  - gitagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.gitops.com
  resources:
  - gitagents/status
  verbs:
  - get
