apiVersion: aws.gitops.com/v1alpha1
kind: Gitagent
metadata:
  name: gitagent-test
spec:
  # Add fields here
  aws-service: "lb"
  tags: 
    kubernetes.io/service-name: "sentry-app/t6"
  git:
    url: "git@gitlab.myteksi.net:dakota/sgbank-terraform.git"  
    file: "providers/aws/sg/central/dns/private_zone/terraform.tfvars"
    keyvar: "datadev-istio-controller-elb"
    fs: "="

